

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app     
    working_dir: /app  
    command: ["streamlit", "run", "dashboard/app1.py", "--server.port=8501", "--server.address=0.0.0.0"]
